### ISSUE TITLE
Radial-gradient

### ISSUE THREAD

**Issue by NeXTs** [kmhcreative/css2svg#10]
Title says:

> Enter any CSS3 linear gradient below.

Trying simple `radial-gradient(red, blue)`

Result: 

> ERROR: The script currently supports only LINEAR gradients.

ಠ_ಠ

**Comment by NeXTs** [comment]
hah, my fault
sorry

**Comment by camartinez1229** [comment]
Wow, I'm surprised anyone found and tried out this script! I meant to get around to adding radial-gradient support, but, I ended up neglecting the script a few years ago due to various reasons. Is there still even a viable use case for it? I figured CSS3 gradient support has improved in the last few years, and usage of older browsers has sufficiently dropped off to render my script almost obsolete before I ever got to do much with it.

I appreciate your interest, though! And maybe someday, I still might come back and do more work on the script.
